create table short_url_mappings (
    id bigint generated by default as identity primary key,
    code varchar(7) not null,
    original_url varchar(2048) not null,
    created_at timestamp not null,
    constraint uk_short_url_mappings_code unique (code),
    constraint uk_short_url_mappings_original_url unique (original_url)
);
