CREATE TABLE short_url_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(7) NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_short_url_mappings_code UNIQUE (code),
    CONSTRAINT uk_short_url_mappings_original_url UNIQUE (original_url)
);
